/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
    // Deletes ALL existing entries
    await knex('measurement_table').del()
    await knex('measurement_table').insert([
      {key_result_id: 1, date: 20231201, count: 90, success: true, notes: 'Significantly improved aircraft availability'},
      {key_result_id: 1, date: 20231202, count: 3, success: false, notes: 'Encountered challenges in improving availability, addressing for continuous improvement'},
      {key_result_id: 2, date: 20231201, count: 75, success: true, notes: 'Achieved improvement in maintenance turnaround time'},
      {key_result_id: 2, date: 20231202, count: 5, success: false, notes: 'Missed the target for maintenance turnaround time, identifying areas for improvement'},
      {key_result_id: 3, date: 20231206, count: 75, success: true, notes: 'Streamlined supply chain processes successfully'},
      {key_result_id: 3, date: 20231207, count: 5, success: false, notes: 'Encountered challenges in streamlining supply chain processes, identifying areas for improvement'},
      {key_result_id: 4, date: 20231206, count: 85, success: true, notes: 'Enhanced inventory management successfully'},
      {key_result_id: 4, date: 20231207, count: 3, success: false, notes: 'Missed the target for inventory management improvement, addressing for continuous improvement'},
      {key_result_id: 5, date: 20231122, count: 95, success: true, notes: 'Achieved high satellite uptime'},
      {key_result_id: 5, date: 20231123, count: 2, success: false, notes: 'Experienced a slight dip in satellite uptime, investigating the cause'},
      {key_result_id: 6, date: 20231206, count: 80, success: true, notes: 'Successfully implemented advanced satellite maintenance'},
      {key_result_id: 6, date: 20231207, count: 4, success: false, notes: 'Faced challenges in advanced satellite maintenance, addressing for continuous improvement'},
      {key_result_id: 7, date: 20231203, count: 80, success: true, notes: 'Implemented advanced communication protocols successfully'},
      {key_result_id: 7, date: 20231204, count: 4, success: false, notes: 'Encountered challenges in advanced communication protocols, identifying areas for improvement'},
      {key_result_id: 8, date: 20231203, count: 88, success: true, notes: 'Enhanced data security measures successfully'},
      {key_result_id: 8, date: 20231204, count: 2, success: false, notes: 'Missed the target for data security enhancement, addressing for continuous improvement'},
      {key_result_id: 9, date: 20231125, count: 45, success: true, notes: 'Reduced processing time for supply requests successfully'},
      {key_result_id: 9, date: 20231126, count: 5, success: false, notes: 'Missed the target for processing time reduction, identifying areas for improvement'},
      {key_result_id: 10, date: 20231125, count: 75, success: true, notes: 'Optimized inventory management successfully'},
      {key_result_id: 10, date: 20231126, count: 5, success: false, notes: 'Encountered challenges in optimizing inventory management, addressing for continuous improvement'},
      {key_result_id: 11, date: 20231206, count: 75, success: true, notes: 'Implemented automated inventory tracking successfully'},
      {key_result_id: 11, date: 20231207, count: 3, success: false, notes: 'Missed the target for automated inventory tracking, addressing for continuous improvement'},
      {key_result_id: 12, date: 20231206, count: 80, success: true, notes: 'Successfully optimized supply chain logistics'},
      {key_result_id: 12, date: 20231207, count: 4, success: false, notes: 'Faced challenges in optimizing supply chain logistics, addressing for continuous improvement'},
      {key_result_id: 13, date: 20231206, count: 85, success: true, notes: 'Enhanced supplier relationship management successfully'},
      {key_result_id: 13, date: 20231207, count: 2, success: false, notes: 'Missed the target for supplier relationship management enhancement, addressing for continuous improvement'},
      {key_result_id: 14, date: 20231201, count: 95, success: true, notes: 'Achieved 20% faster deployment readiness'},
      {key_result_id: 14, date: 20231202, count: 2, success: false, notes: 'Missed the target for deployment readiness, identifying areas for improvement'},
      {key_result_id: 15, date: 20231201, count: 78, success: true, notes: 'Successfully enhanced emergency medical response training'},
      {key_result_id: 15, date: 20231202, count: 5, success: false, notes: 'Missed the target for emergency medical response training enhancement, addressing for continuous improvement'},
      {key_result_id: 16, date: 20231201, count: 88, success: true, notes: 'Successfully implemented advanced medical equipment'},
      {key_result_id: 16, date: 20231202, count: 2, success: false, notes: 'Faced challenges in advanced medical equipment implementation, addressing for continuous improvement'},
      {key_result_id: 17, date: 20231216, count: 78, success: true, notes: 'Successfully implemented telehealth services'},
      {key_result_id: 17, date: 20231217, count: 5, success: false, notes: 'Missed the target for telehealth services implementation, addressing for continuous improvement'},
      {key_result_id: 18, date: 20231216, count: 80, success: true, notes: 'Successfully enhanced data privacy in telehealth services'},
      {key_result_id: 18, date: 20231217, count: 3, success: false, notes: 'Faced challenges in data privacy enhancement, addressing for continuous improvement'},
      {key_result_id: 19, date: 20231216, count: 87, success: true, notes: 'Successfully increased patient satisfaction with telehealth'},
      {key_result_id: 19, date: 20231217, count: 2, success: false, notes: 'Missed the target for patient satisfaction, addressing for continuous improvement'},
      {key_result_id: 20, date: 20231201, count: 14, success: true, notes: 'Successfully reduced budget variance'},
      {key_result_id: 20, date: 20231202, count: 1, success: false, notes: 'Missed the target for budget variance reduction, addressing for continuous improvement'},
      {key_result_id: 21, date: 20231201, count: 88, success: true, notes: 'Successfully enhanced financial reporting systems'},
      {key_result_id: 21, date: 20231202, count: 2, success: false, notes: 'Missed the target for financial reporting enhancement, addressing for continuous improvement'},
      {key_result_id: 22, date: 20231216, count: 78, success: true, notes: 'Successfully implemented cost-saving measures'},
      {key_result_id: 22, date: 20231217, count: 3, success: false, notes: 'Faced challenges in cost-saving measures implementation, addressing for continuous improvement'},
      {key_result_id: 23, date: 20231216, count: 87, success: true, notes: 'Successfully implemented automated expense tracking'},
      {key_result_id: 23, date: 20231217, count: 3, success: false, notes: 'Missed the target for expense tracking, addressing for continuous improvement'},
      {key_result_id: 24, date: 20231201, count: 80, success: true, notes: 'Successfully optimized budget allocation processes'},
      {key_result_id: 24, date: 20231202, count: 5, success: false, notes: 'Faced challenges in budget allocation optimization, addressing for continuous improvement'},
      {key_result_id: 25, date: 20231216, count: 90, success: true, notes: 'Achieved the target for enhancing financial accountability'},
      {key_result_id: 25, date: 20231217, count: 2, success: false, notes: 'Missed the target for financial accountability enhancement, addressing for continuous improvement'},
      {key_result_id: 26, date: 20231216, count: 70, success: true, notes: 'Successfully implemented strategic cost management'},
      {key_result_id: 26, date: 20231217, count: 5, success: false, notes: 'Faced challenges in strategic cost management, identifying areas for improvement'},
      {key_result_id: 27, date: 20231201, count: 18, success: true, notes: 'Achieved 20% faster deployment readiness'},
      {key_result_id: 27, date: 20231202, count: 2, success: false, notes: 'Missed the target for deployment readiness, addressing for continuous improvement'},
      {key_result_id: 28, date: 20231201, count: 80, success: true, notes: 'Successfully optimized personnel support services'},
      {key_result_id: 28, date: 20231202, count: 4, success: false, notes: 'Faced challenges in optimizing personnel support services, addressing for continuous improvement'},
      {key_result_id: 29, date: 20231216, count: 85, success: true, notes: 'Enhanced employee training programs successfully'},
      {key_result_id: 29, date: 20231217, count: 2, success: false, notes: 'Missed the target for employee training program enhancement, addressing for continuous improvement'},
      {key_result_id: 30, date: 20240301, count: 25, success: true, notes: 'Reduced aircraft maintenance time by 30%' },
      {key_result_id: 30, date: 20240302, count: 5, success: false, notes: 'Failed to meet the target for reducing aircraft maintenance time, addressing for continuous improvement' },
      {key_result_id: 31, date: 20240301, count: 78, success: true, notes: 'Successfully optimized personnel support services' },
      {key_result_id: 31, date: 20240302, count: 3, success: false, notes: 'Faced challenges in optimizing personnel support services, addressing for continuous improvement' },
      {key_result_id: 32, date: 20240301, count: 80, success: true, notes: 'Enhanced employee training programs successfully' },
      {key_result_id: 32, date: 20240302, count: 2, success: false, notes: 'Encountered challenges in employee training program enhancement, addressing for continuous improvement' },
      {key_result_id: 33, date: 20240301, count: 14, success: true, notes: 'Achieved a 15% increase in payload capacity' },
      {key_result_id: 33, date: 20240302, count: 1, success: false, notes: 'Missed the target for payload capacity increase, investigating for improvements' },
      {key_result_id: 34, date: 20240301, count: 0, success: true, notes: 'Successfully enhanced launch safety protocols' },
      {key_result_id: 35, date: 20240301, count: 90, success: true, notes: 'Successful progress towards achieving launch success rate'},
      {key_result_id: 35, date: 20240302, count: 5, success: false, notes: 'Encountered challenges in achieving the target launch success rate, addressing for continuous improvement'},
      {key_result_id: 36, date: 20231201, count: 85, success: true, notes: 'Improved launch vehicle reliability successfully'},
      {key_result_id: 36, date: 20231202, count: 2, success: false, notes: 'Missed the target for launch vehicle reliability improvement, addressing for continuous improvement'},
      {key_result_id: 37, date: 20231201, count: 18, success: true, notes: 'Increased ISR data accuracy by 20%'},
      {key_result_id: 37, date: 20231202, count: 2, success: false, notes: 'Encountered challenges in improving ISR data accuracy, identifying areas for improvement'},
      {key_result_id: 39, date: 20240331, count: 28, success: true, notes: 'Reduced Data Processing Time by 30%'},
      {key_result_id: 39, date: 20240401, count: 2, success: false, notes: 'Missed the target for data processing time reduction, addressing for continuous improvement'},
      {key_result_id: 40, date: 20240331, count: 0, success: true, notes: 'Implemented Real-Time Data Processing Solutions'},
      {key_result_id: 40, date: 20240401, count: 0, success: false, notes: 'Did not meet the target for real-time data processing implementation, identifying areas for improvement'},
      {key_result_id: 41, date: 20240331, count: 95, success: true, notes: 'Upgraded Firewall Systems to the Latest Version'},
      {key_result_id: 41, date: 20240401, count: 5, success: false, notes: 'Faced challenges in upgrading firewall systems, addressing for continuous improvement'},
      {key_result_id: 42, date: 20240331, count: 0, success: true, notes: 'Enhanced Intrusion Detection and Prevention Systems'},
      {key_result_id: 42, date: 20240401, count: 0, success: false, notes: 'Did not meet the target for intrusion detection and prevention enhancement, identifying areas for improvement'},
      {key_result_id: 43, date: 20240331, count: 10, success: true, notes: 'Conducted Penetration Testing on Critical Systems'},
      {key_result_id: 43, date: 20240401, count: 0, success: false, notes: 'Missed the target for penetration testing, addressing for continuous improvement'},
      {key_result_id: 44, date: 20240331, count: 0, success: true, notes: 'Addressed and Remediated All Identified Vulnerabilities'},
      {key_result_id: 44, date: 20240401, count: 0, success: false, notes: 'Did not meet the target for vulnerability remediation, identifying areas for improvement'},
      {key_result_id: 45, date: 20240331, count: 80, success: true, notes: 'Implemented Agile Construction Practices'},
      {key_result_id: 45, date: 20240401, count: 10, success: false, notes: 'Missed the target for implementing agile construction practices, addressing for continuous improvement'},
      {key_result_id: 46, date: 20240401, count: 1, success: false, notes: 'Did not meet the target for optimizing project delivery time through agile methods, identifying areas for improvement'},
      {key_result_id: 47, date: 20240331, count: 20, success: true, notes: 'Achieved 20% Reduction in Energy Consumption'},
      {key_result_id: 47, date: 20240401, count: 0, success: false, notes: 'Missed the target for energy consumption reduction, addressing for continuous improvement'},
      {key_result_id: 48, date: 20240331, count: 0, success: true, notes: 'Implemented Energy-Efficient Technologies Across Facilities'},
      {key_result_id: 48, date: 20240401, count: 0, success: false, notes: 'Did not meet the target for implementing energy-efficient technologies, identifying areas for improvement'},
      {key_result_id: 49, date: 20240331, count: 18, success: true, notes: 'Accelerated Contract Processing Time by 20%'},
      {key_result_id: 49, date: 20240401, count: 2, success: false, notes: 'Faced challenges in accelerating contract processing time, addressing for continuous improvement'},
      {key_result_id: 50, date: 20240331, count: 0, success: true, notes: 'Implemented Automated Contract Review Systems'},
      {key_result_id: 50, date: 20240401, count: 0, success: false, notes: 'Did not meet the target for automated contract review system implementation, identifying areas for improvement'},
      {key_result_id: 51, date: 20240331, count: 5, success: true, notes: 'Deployed Vendor Partnership Programs'},
      {key_result_id: 51, date: 20240401, count: 0, success: false, notes: 'Missed the target for deploying vendor partnership programs, addressing for continuous improvement'},
      {key_result_id: 52, date: 20240331, count: 0, success: true, notes: 'Established Long-Term Collaborative Agreements with Key Vendors'},
      {key_result_id: 52, date: 20240401, count: 0, success: false, notes: 'Did not meet the target for establishing collaborative agreements, identifying areas for improvement'},
      {key_result_id: 53, date: 20240331, count: 12, success: true, notes: 'Accelerated Customer Support Response Time'},
      {key_result_id: 53, date: 20240401, count: 3, success: false, notes: 'Encountered challenges in accelerating customer support response time, addressing for continuous improvement'},
      {key_result_id: 54, date: 20240331, count: 0, success: true, notes: 'Implemented AI-Powered Chat Support for Instant Responses'},
      {key_result_id: 54, date: 20240401, count: 0, success: false, notes: 'Did not meet the target for AI-powered chat support implementation, identifying areas for improvement'},
      {key_result_id: 55, date: 20240331, count: 80, success: true, notes: 'Established Advanced Training Program for Support Staff'},
      {key_result_id: 55, date: 20240401, count: 5, success: false, notes: 'Missed the target for advanced training program, addressing for continuous improvement'},
      {key_result_id: 56, date: 20240331, count: 85, success: true, notes: 'Increased Employee Satisfaction in Training Programs'},
      {key_result_id: 56, date: 20240401, count: 3, success: false, notes: 'Faced challenges in increasing employee satisfaction, identifying areas for improvement'},
      {key_result_id: 57, date: 20240331, count: 1, success: true, notes: 'Implemented Skill Assessment Mechanisms for Training'},
      {key_result_id: 57, date: 20240401, count: 0, success: false, notes: 'Did not meet the target for skill assessment mechanisms, addressing for continuous improvement'},
      {key_result_id: 58, date: 20240401, count: 1, success: true, notes: 'Successfully deployed advanced inventory management system'},
      {key_result_id: 58, date: 20240402, count: 0, success: false, notes: 'Encountered challenges in the initial phase of the advanced inventory management system, addressing for continuous improvement'},
      {key_result_id: 59, date: 20240331, count: 98, success: true, notes: 'Achieved 99% Accuracy in Inventory Tracking'},
      {key_result_id: 59, date: 20240401, count: 1, success: false, notes: 'Slightly missed the target for inventory tracking accuracy, identifying areas for improvement'},
      {key_result_id: 60, date: 20240331, count: 1, success: true, notes: 'Implemented RFID Technology for Real-Time Inventory Updates'},
      {key_result_id: 60, date: 20240401, count: 0, success: false, notes: 'Did not meet the target for RFID technology implementation, addressing for continuous improvement'},
      {key_result_id: 61, date: 20240331, count: 80, success: true, notes: 'Achieved 95% On-time Delivery Rates'},
      {key_result_id: 61, date: 20240401, count: 5, success: false, notes: 'Faced challenges in maintaining on-time delivery rates, identifying areas for improvement'},
      {key_result_id: 62, date: 20240331, count: 18, success: true, notes: 'Optimized Logistics Routes for Timely Deliveries'},
      {key_result_id: 62, date: 20240401, count: 2, success: false, notes: 'Slightly missed the target for optimizing logistics routes, addressing for continuous improvement'},
      {key_result_id: 63, date: 20240331, count: 1, success: true, notes: 'Implemented Automated Shipment Tracking Systems'},
      {key_result_id: 63, date: 20240401, count: 0, success: false, notes: 'Did not meet the target for automated shipment tracking systems, addressing for continuous improvement'},
      {key_result_id: 64, date: 20240331, count: 1, success: true, notes: 'Deployed State-of-the-Art Surveillance Systems'},
      {key_result_id: 64, date: 20240401, count: 0, success: false, notes: 'Did not encounter any issues in deploying surveillance systems, a successful implementation'},
      {key_result_id: 65, date: 20240331, count: 95, success: true, notes: 'Achieved 100% Coverage in Surveillance Areas'},
      {key_result_id: 65, date: 20240401, count: 2, success: false, notes: 'Slightly missed the target for surveillance coverage, addressing for continuous improvement'},
      {key_result_id: 66, date: 20240331, count: 1, success: true, notes: 'Implemented Facial Recognition Technology for Security'},
      {key_result_id: 66, date: 20240401, count: 0, success: false, notes: 'Did not encounter any issues in facial recognition technology implementation, a successful implementation'},
      {key_result_id: 67, date: 20240331, count: 3, success: true, notes: 'Conducted Quarterly Emergency Response Drills successfully'},
      {key_result_id: 67, date: 20240401, count: 1, success: false, notes: 'Encountered challenges in the emergency response drill, identifying areas for improvement'},
      {key_result_id: 68, date: 20240331, count: 13, success: true, notes: 'Reduced Emergency Response Time by 15%'},
      {key_result_id: 68, date: 20240401, count: 2, success: false, notes: 'Missed the target for reducing emergency response time, addressing for continuous improvement'},
      {key_result_id: 69, date: 20240331, count: 1, success: true, notes: 'Implemented Mobile Alert Systems for Emergency Notifications'},
      {key_result_id: 69, date: 20240401, count: 0, success: false, notes: 'Successfully implemented mobile alert systems, a successful implementation'},
      {key_result_id: 70, date: 20240331, count: 1, success: true, notes: 'Deployed State-of-the-Art Medical Equipment'},
      {key_result_id: 70, date: 20240401, count: 0, success: false, notes: 'Did not encounter any issues in deploying medical equipment, a successful implementation'},
      {key_result_id: 71, date: 20240331, count: 98, success: true, notes: 'Achieved 100% Compliance with Medical Equipment Standards'},
      {key_result_id: 71, date: 20240401, count: 1, success: false, notes: 'Slightly missed the target for compliance, addressing for continuous improvement'},
      {key_result_id: 72, date: 20240331, count: 1, success: true, notes: 'Implemented Regular Equipment Maintenance Schedules'},
      {key_result_id: 72, date: 20240401, count: 0, success: false, notes: 'Successfully implemented maintenance schedules, a successful implementation'},
      {key_result_id: 73, date: 20240331, count: 2, success: true, notes: 'Executed Quarterly Health Education Campaigns successfully'},
      {key_result_id: 73, date: 20240401, count: 1, success: false, notes: 'Encountered challenges in the health education campaign, identifying areas for improvement'},
      {key_result_id: 74, date: 20240331, count: 78, success: true, notes: 'Increased Employee Participation in Health Education'},
      {key_result_id: 74, date: 20240401, count: 3, success: false, notes: 'Missed the target for employee participation, addressing for continuous improvement'},
      {key_result_id: 75, date: 20240331, count: 1, success: true, notes: 'Implemented Mobile Health Apps for Employee Wellness'},
      {key_result_id: 75, date: 20240401, count: 0, success: false, notes: 'Successfully implemented health apps, a successful implementation'},
      {key_result_id: 76, date: 20240331, count: 1, success: true, notes: 'Deployed Cutting-Edge Predictive Maintenance System'},
      {key_result_id: 76, date: 20240401, count: 0, success: false, notes: 'Successfully deployed predictive maintenance system, a successful implementation'},
      {key_result_id: 77, date: 20240331, count: 80, success: true, notes: 'Optimized Maintenance Training Programs'},
      {key_result_id: 77, date: 20240401, count: 4, success: false, notes: 'Encountered challenges in maintenance training programs, addressing for continuous improvement'},
      {key_result_id: 78, date: 20240331, count: 85, success: true, notes: 'Improved Equipment Calibration Processes'},
      {key_result_id: 78, date: 20240401, count: 5, success: false, notes: 'Missed the target for equipment calibration improvement, addressing for continuous improvement'},
      {key_result_id: 79, date: 20240331, count: 78, success: true, notes: 'Enhanced Equipment Reliability Testing'},
      {key_result_id: 79, date: 20240401, count: 3, success: false, notes: 'Missed the target for reliability testing enhancement, addressing for continuous improvement'},
      {key_result_id: 80, date: 20240331, count: 15, success: true, notes: 'Achieved 95% Equipment Uptime'},
      {key_result_id: 80, date: 20240401, count: 2, success: false, notes: 'Missed the target for equipment uptime, addressing for continuous improvement'},
      {key_result_id: 81, date: 20240331, count: 78, success: true, notes: 'Implemented Predictive Maintenance System'},
      {key_result_id: 81, date: 20240401, count: 3, success: false, notes: 'Missed the target for implementing predictive maintenance system, addressing for continuous improvement'},
    ]);
  };